spring.application.name=openai
spring.ai.google.genai.apiKey=${GOOGLE-API_KEY}
spring.ai.google.genai.embedding.api-key=${GOOGLE-API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
#spring.ai.google.genai.chat.options.include-thoughts=true
spring.ai.google.genai.chat.options.temperature=0.7
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.options.dimensions=1536

spring.datasource.url=jdbc:mariadb://localhost:3308/vector_phone_specs
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.ai.vectorstore.mariadb.initialize-schema=true
spring.ai.vectorstore.mariadb.distance-type=cosine
spring.ai.vectorstore.mariadb.dimensions=1536


MOBILE_API_KEY=${MOBILE_API_KEY}
EXCHANGE_RATE_KEY=${EXCHANGE_RATE_KEY}
